GRANT 
SELECT, 
SHOW VIEW ON *.* 
TO 'evaalonso'@'localhost';
ALTER USER 'evaalonso'@'localhost' 
REQUIRE NONE 
WITH 
MAX_QUERIES_PER_HOUR 100
MAX_CONNECTIONS_PER_HOUR 100
MAX_UPDATES_PER_HOUR 100 
MAX_USER_CONNECTIONS 100;